export interface MenuItem {
  code?: string;
  category: string;
  name: string;
  price: number;
  description?: string;
}

export const menuData: MenuItem[] = [
  { category: 'Kampanya Menüler', code: '280', name: 'Patso Menü', price: 249, description: 'Sade Patso ve Ayran' },
  { category: 'Kampanya Menüler', code: '281', name: 'Piliç Dürüm Menü', price: 299, description: 'Piliç Şiş Dürüm, Patates ve Ayran' },
  { category: 'Kampanya Menüler', code: '282', name: 'Burger Menü', price: 469, description: '100gr Dana Burger, Pataes ve Kutu İçecek' },
  { category: 'Kampanya Menüler', code: '283', name: 'Arabiata Makarna Menü', price: 369, description: 'Penne makarna, zeytin, sarımsak, acı biberli napolitan sos ve Kutu İçecek' },
  { category: 'Kampanya Menüler', code: '284', name: 'Kaşarlı Tost Menü', price: 159, description: 'Kaşarlı Tost ve Bardak Çay' },
  { category: 'Kampanya Menüler', code: '286', name: 'Çikolatalı Tost Menü', price: 219, description: 'Çikolatalı Tost ve Bardak Çay' },
  { category: 'Kampanya Menüler', code: '285', name: 'Kahve - Kurabiye Menü', price: 179, description: 'Sade / Sütlü Kahve ve Çikolatalı Kurabiye' },

  { category: 'Tostlar', code: '151', name: 'Kaşarlı Tost', price: 139 },
  { category: 'Tostlar', code: '152', name: 'Kepekli Beyaz Peynirli Tost', price: 169 },
  { category: 'Tostlar', code: '154', name: 'Karışık Tost', price: 239, description: 'Kangal Sucuk, Kaşar' },
  { category: 'Tostlar', code: '156', name: 'Çikolatalı Tost', price: 189 },
  { category: 'Tostlar', code: '157', name: 'Adeks Tost', price: 319, description: 'Kaşar, kangal sucuk, domates, biber ve nefis Adeks Sos ile' },

  { category: 'Burgerler', code: '201', name: 'Cajun Piliç Burger (100gr)', price: 309, description: 'Kızarmış patates ile servis edilir.' },
  { category: 'Burgerler', code: '209', name: 'Çıtır Piliç Burger (100gr)', price: 299, description: 'Kızarmış patates ile servis edilir.' },
  { category: 'Burgerler', code: '202', name: 'Hamburger (100gr)', price: 419, description: 'Kızarmış patates ile servis edilir.' },
  { category: 'Burgerler', code: '203', name: 'Cheeseburger (100gr)', price: 439, description: 'Kızarmış patates ile servis edilir.' },
  { category: 'Burgerler', code: '205', name: 'Bomba Burger', price: 399, description: 'Sosis, sucuk, kornişon turşu, kaşar, yumurta. Kızarmış patates ile servis edilir.' },
  { category: 'Burgerler', code: '206', name: 'Double Burger (200gr)', price: 679, description: 'Çift burger köftesi ve çedar peyniri. Kızarmış patates ile servis edilir.' },
  { category: 'Burgerler', code: '208', name: 'Adeks Burger (150gr)', price: 579, description: 'Özel hamburger köftesi, karamelize soğan, çedar ve nefis Adeks Sos ile. Kızarmış patates ile servis edilir.' },

  { category: 'Patso ve Aperatifler', code: '271', name: 'Günün Çorbası', price: 109 },
  { category: 'Patso ve Aperatifler', code: '351', name: 'Sade Patso', price: 209 },
  { category: 'Patso ve Aperatifler', code: '352', name: 'Sosisli Patso', price: 269 },
  { category: 'Patso ve Aperatifler', code: '353', name: 'Sucuklu Patso', price: 299 },
  { category: 'Patso ve Aperatifler', code: '251', name: 'Parmak Patates', price: 169 },
  { category: 'Patso ve Aperatifler', code: '252', name: 'Soğan Halkası 10 Adet', price: 149 },
  { category: 'Patso ve Aperatifler', code: '254', name: 'Çıtır Piliç Parçaları (350gr)', price: 319 },
  { category: 'Patso ve Aperatifler', code: '256', name: 'Combo Sepeti', price: 379, description: '6 adet soğan halkası, 4 adet kokteyl sosis, 200gr çıtır piliç patates kızartması' },
  { category: 'Patso ve Aperatifler', code: '451', name: 'Piliç Quesadilla', price: 369, description: 'Tortilla ekmeği arasında sote edilmiş piliç, mantar, renkli biber ve kaşar. Patates kızartması ve salsa sos ile' },
  { category: 'Patso ve Aperatifler', code: '452', name: 'Sebzeli Quesadilla', price: 339, description: 'Tortilla ekmeği arasında sote edilmiş mantar, renkli biber ve kaşar. Patates kızartması ve salsa sos ile' },

  { category: 'Dürüm', code: '402', name: 'Piliç Şiş Dürüm', price: 269, description: 'Tortilla ekmeği içine sarılmış çeşitli lezzetler; marul, domates ve kızarmış patates ile servis edilir.' },
  { category: 'Dürüm', code: '403', name: 'Acılı Cajun Piliç Dürüm', price: 299, description: 'Dürüm İçerisine patates, çedar ve acı sos. Tortilla ekmeği içine sarılmış çeşitli lezzetler; marul, domates ve kızarmış patates ile servis edilir.' },
  { category: 'Dürüm', code: '404', name: 'Mantarlı Piliç Şiş Dürüm', price: 309, description: 'Tortilla ekmeği içine sarılmış çeşitli lezzetler; marul, domates ve kızarmış patates ile servis edilir.' },
  { category: 'Dürüm', code: '405', name: 'Çıtır Piliç Dürüm', price: 299, description: 'Tortilla ekmeği içine sarılmış çeşitli lezzetler; marul, domates ve kızarmış patates ile servis edilir.' },
  { category: 'Dürüm', code: '407', name: 'Et Döner Dürüm', price: 459, description: 'Tortilla ekmeği içine sarılmış çeşitli lezzetler; marul, domates ve kızarmış patates ile servis edilir.' },
  { category: 'Dürüm', code: '408', name: 'Köfte Dürüm', price: 439, description: 'Tortilla ekmeği içine sarılmış çeşitli lezzetler; marul, domates ve kızarmış patates ile servis edilir.' },

  { category: 'Makarnalar', code: '501', name: 'Penne Arabiata', price: 269, description: 'Zeytin, sarımsak ve acı biberli napolitan sos' },
  { category: 'Makarnalar', code: '502', name: 'Fettuccine Alfredo', price: 399, description: 'Krema, mantar, renkli biber, pesto sos ve parmesan' },
  { category: 'Makarnalar', code: '503', name: 'Spagetti Bolognese', price: 389, description: 'Kıymalı napolitan sos, parmesan' },
  { category: 'Makarnalar', code: '507', name: 'Fettuccine Belle', price: 489, description: 'Krema, mantar, jülyen tavuk parçaları, renkli biber, pesto sos ve parmesan' },
  { category: 'Makarnalar', code: '508', name: 'Fettuccine Bisteca', price: 589, description: 'Sotelenmiş kontrfile parçaları, renkli biber ve napolitan sos' },

  { category: 'Salatalar', code: '551', name: 'Akdeniz Salata', price: 339, description: 'Akdeniz yeşillikleri, beyaz peynir, siyah zeytin, domates, mısır zeytinyağı ve limon sos ile' },
  { category: 'Salatalar', code: '553', name: 'Cajun Piliç Salata', price: 379, description: 'Akdeniz yeşillikleri, cajun baharatı ile pane edilmiş tavuk parçaları, kaşar domates, salatalık, dilim zeytin ve hardal sos ile' },
  { category: 'Salatalar', code: '554', name: 'Çıtır Piliç Salata', price: 389, description: 'Akdeniz yeşillikleri, çıtır piliç parçaları, kaşar, domates, salatalık, dilim zeytin ve mayonezli yeşil sos ile' },
  { category: 'Salatalar', code: '557', name: 'Sezar Salata', price: 399, description: 'Akdeniz yeşillikleri, ızgara jülyen tavuk parçaları, kaşar, domates, salatalık kruton ekmek, sezar sos ile' },
  { category: 'Salatalar', code: '558', name: 'Kontrfile Salata', price: 539, description: 'Akdeniz yeşillikleri üzerine ızgara jülyen kontrfile parçaları, kaşar, domates salatalık, kruton ekmek ve limonlu sos ile' },

  { category: 'Ana Yemekler', code: '601', name: 'Çökertme Kebabı tavuklu', price: 329, description: 'Yoğurtlu kibrit patates üzerinde taze baharatla marine edilip tereyağlı domates sos ile sotelenmiş tavuk' },
  { category: 'Ana Yemekler', code: '602', name: 'Çökertme Kebabı et dönerli', price: 469, description: 'Yoğurtlu kibrit patates üzerinde taze baharatla marine edilip tereyağlı domates sos ile sotelenmiş et döner' },
  { category: 'Ana Yemekler', code: '603', name: 'Çökertme Kebabı kontrfile', price: 499, description: 'Yoğurtlu kibrit patates üzerinde taze baharatla marine edilip tereyağlı domates sos ile sotelenmiş kontrfile parçaları' },
  { category: 'Ana Yemekler', code: '606', name: 'Piliç Izgara', price: 329, description: 'Izgara piliç fileto, salata ve patates kızartması' },
  { category: 'Ana Yemekler', code: '605', name: 'Piliç Meksika', price: 339, description: 'Taze baharatla marine edilmiş ızgara piliç üzerine acılı meksika sosu jalapeno, renkli biber ve patates kızartması' },
  { category: 'Ana Yemekler', code: '609', name: 'Piliç Emense', price: 369, description: 'Jülyen tavuk parçaları, hardallı dömi glas sos, renkli biber, taze baharatlar, krema ve patates kızartması' },
  { category: 'Ana Yemekler', code: '613', name: 'Piliç Şinitzel', price: 329, description: 'Piliç filetosu üzerinde tereyağı, limon, salata ve patates kızartması' },
  { category: 'Ana Yemekler', code: '610', name: 'Piliç Mushroom', price: 489, description: 'Piliç filetosu üzerine sotelenmiş mantar, kırmızı biber, krema, eritilmiş kaşar ve patates kızartması' },
  { category: 'Ana Yemekler', code: '607', name: 'Cafe de Paris Soslu Tavuk', price: 499, description: 'Jülyen tavuk parçaları, patates kızartması, salata ve pesto soslu penne makarna' },
  { category: 'Ana Yemekler', code: '608', name: 'Köri Soslu Tavuk', price: 479, description: 'Köri sosu ile sotelenmiş tavuk parçaları, patates kızartması, salata ve pesto soslu penne makarna' },
  { category: 'Ana Yemekler', code: '604', name: 'Izgara Köfte', price: 519, description: 'Izgara köfte yanında mevsim yeşilliği, ızgara biber ve patates kızartması' },
  { category: 'Ana Yemekler', code: '614', name: 'Adeks Dürüm', price: 669, description: 'Kontrfile, soya sosu, soğan ve nefis Adeks Sos. Yoğurt, çedar patates kızartması ve salata ile tabakta servis edilir.' },

  { category: 'Sıcak İçecekler', code: '851', name: 'Bardak Çay', price: 40 },
  { category: 'Sıcak İçecekler', code: '852', name: 'Fincan Çay', price: 70 },
  { category: 'Sıcak İçecekler', code: '853', name: 'Bitki Çayları', price: 85 },
  { category: 'Sıcak İçecekler', code: '806', name: 'Espresso', price: 129 },
  { category: 'Sıcak İçecekler', code: '807', name: 'Double Espresso', price: 149 },
  { category: 'Sıcak İçecekler', code: '808', name: 'Espresso Macchiato', price: 129 },
  { category: 'Sıcak İçecekler', code: '809', name: 'Türk Kahvesi', price: 129 },
  { category: 'Sıcak İçecekler', code: '810', name: 'Double Türk Kahvesi', price: 149 },
  { category: 'Sıcak İçecekler', code: '801', name: 'Filtre Kahve', price: 139 },
  { category: 'Sıcak İçecekler', code: '802', name: 'Americano', price: 139 },
  { category: 'Sıcak İçecekler', code: '803', name: 'Latte', price: 179 },
  { category: 'Sıcak İçecekler', code: '804', name: 'Cappuccino', price: 179 },
  { category: 'Sıcak İçecekler', code: '805', name: 'Cafe Mocha', price: 219 },
  { category: 'Sıcak İçecekler', code: '881', name: 'Sıcak Çikolata', price: 219 },
  { category: 'Sıcak İçecekler', code: '882', name: 'Ballı Süt', price: 219 },
  { category: 'Sıcak İçecekler', code: '883', name: 'Salep', price: 219 },

  { category: 'Soğuk Kahveler', code: '771', name: 'Iced Americano', price: 189 },
  { category: 'Soğuk Kahveler', code: '772', name: 'Iced Cafe Latte', price: 219 },
  { category: 'Soğuk Kahveler', code: '773', name: 'Iced Caramel Macchiato', price: 239 },
  { category: 'Soğuk Kahveler', code: '774', name: 'Iced Cafe Mocha', price: 239 },

  { category: 'Frappe', code: '775', name: 'Vanilya Frappe', price: 239 },
  { category: 'Frappe', code: '776', name: 'Çikolata Frappe', price: 239 },
  { category: 'Frappe', code: '777', name: 'Karamel Frappe', price: 239 },

  { category: 'Soğuk İçecekler', code: '766', name: 'Su', price: 30 },
  { category: 'Soğuk İçecekler', code: '709', name: 'Soda', price: 45 },
  { category: 'Soğuk İçecekler', code: '710', name: 'Limonlu Soda', price: 60 },
  { category: 'Soğuk İçecekler', code: '712', name: 'Elmalı Soda', price: 60 },
  { category: 'Soğuk İçecekler', code: '715', name: 'Mango&Ananas Soda', price: 60 },
  { category: 'Soğuk İçecekler', code: '716', name: 'Karpuz&Çilek Soda', price: 60 },
  { category: 'Soğuk İçecekler', code: '761', name: 'Ayran', price: 65 },
  { category: 'Soğuk İçecekler', code: '763', name: 'Özel Şişe Ayran', price: 95 },
  { category: 'Soğuk İçecekler', code: '701', name: 'Kutu İçecekler', price: 90, description: 'Coca-Cola, Fanta, Sprite, Zero, Max' },
  { category: 'Soğuk İçecekler', code: '707', name: 'Beyoğlu Şişe', price: 90 },
  { category: 'Soğuk İçecekler', code: '708', name: 'Coca-Cola 300ml Şişe', price: 90 },
  { category: 'Soğuk İçecekler', code: '768', name: 'Schweppes Bitter Limon', price: 90 },
  { category: 'Soğuk İçecekler', code: '769', name: 'Schweppes Mandalina', price: 90 },
  { category: 'Soğuk İçecekler', code: '721', name: 'Limon Soğuk Çay', price: 90 },
  { category: 'Soğuk İçecekler', code: '722', name: 'Şeftali Soğuk Çay', price: 90 },
  { category: 'Soğuk İçecekler', code: '723', name: 'Mango Soğuk Çay', price: 90 },
  { category: 'Soğuk İçecekler', code: '726', name: 'Karpuz Soğuk Çay', price: 90 },
  { category: 'Soğuk İçecekler', code: '731', name: 'Vişne Suyu', price: 90 },
  { category: 'Soğuk İçecekler', code: '732', name: 'Portakal Suyu', price: 90 },
  { category: 'Soğuk İçecekler', code: '733', name: 'Kayısı Suyu', price: 90 },
  { category: 'Soğuk İçecekler', code: '734', name: 'Şeftali Suyu', price: 90 },
  { category: 'Soğuk İçecekler', code: '735', name: 'Karışık Meyve Suyu', price: 90 },
  { category: 'Soğuk İçecekler', code: '737', name: 'Atom', price: 90 },
  { category: 'Soğuk İçecekler', code: '751', name: 'Limonata', price: 129 },
  { category: 'Soğuk İçecekler', code: '762', name: 'Cool Lime', price: 129 },
  { category: 'Soğuk İçecekler', code: '782', name: 'Karpuz Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '783', name: 'Green Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '784', name: 'Mango Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '785', name: 'Pipeline Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '786', name: 'Rossi Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '787', name: 'Ultra Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '788', name: 'Reserve Monster', price: 169 },
  { category: 'Soğuk İçecekler', code: '753', name: 'Frozen', price: 229 },
  { category: 'Soğuk İçecekler', code: '752', name: 'Milkshake', price: 259 },

  { category: 'Tatlılar', code: '920', name: 'Kurabiye', price: 80 },
  { category: 'Tatlılar', code: '901', name: 'Çikolata Magnolia', price: 259 },
  { category: 'Tatlılar', code: '902', name: 'Çilekli Magnolia', price: 259 },
  { category: 'Tatlılar', code: '903', name: 'Muzlu Magnolia', price: 259 },
  { category: 'Tatlılar', code: '904', name: 'Oreolu Magnolia', price: 259 },
  { category: 'Tatlılar', code: '922', name: 'Meyveli Cheesecake', price: 239 },
  { category: 'Tatlılar', code: '924', name: 'San sebastian Cheesecake', price: 299 },
  { category: 'Tatlılar', code: '932', name: 'Beyaz Çikolatalı Brownie', price: 319, description: 'Dondurma İle' },
  { category: 'Tatlılar', code: '905', name: 'Tiramisu', price: 289 },
  { category: 'Tatlılar', code: '931', name: 'Sufle', price: 319, description: 'Dondurma İle' },
  { category: 'Tatlılar', code: '933', name: 'Dilim Pastalar', price: 259 },
];
